### ISSUE TITLE
Can we have smelting related wire machines?

### ISSUE THREAD

**Issue by bbarry** [Sense101/shapez-industries#3]
It is excessively frustrating to break down a layer containing smelted quadrants into components for a MAM.

So far the only way I've figured out how to do it is
1. make a wire component that has 1000 constant signals representing all 1, 2 or 3 quadrant smelted shapes
2. in parallel figure out which rotations of each are potentially a part of the layer via a cutting wire tool and comparisons
3. if so, check through every combination of every potential match
4. If none of them match, assume it is a 4 quadrant smelted shape

Can we have 1 or both of these machines:

1. a smelter wire machine - 1 input, 1 output; smelts/links the shapes in each layer; for example, given 
2. a linked segment analyzer -  returns the quadrant or linked quadrants containing the top right quadrant of the bottom layer (just like the normal analyzer except that it returns a partial layer with only one linked segment instead of a full layer of that quadrant rotated 4 times)

**Comment by bbarry** [comment]
found https://github.com/SkimnerPhi/wires-plus

**Comment by Sense101** [comment]
yep, wires+ is the way to go for that
